import { v4 as uuid } from 'uuid'
import { db } from './PlanKompasDB'
import type { Plan, StrategicObjective, OperationalObjective, Action, User } from '@/domain/types'

const now = new Date().toISOString()
const SYSTEM = 'system'

export async function seedDatabase() {
  const planCount = await db.plans.count()
  if (planCount > 0) return // Already seeded

  const planId = uuid()
  const sd1Id = uuid()
  const sd2Id = uuid()
  const od1Id = uuid()
  const od2Id = uuid()
  const od3Id = uuid()
  const od4Id = uuid()

  const plan: Plan = {
    id: planId,
    title: 'Actieplan 2025–2026',
    startYear: 2025,
    endYear: 2026,
    description: 'Strategisch actieplan voor het schooljaar 2025–2026',
    isActive: true,
    createdAt: now,
    updatedAt: now,
    createdBy: SYSTEM,
  }

  const sds: StrategicObjective[] = [
    {
      id: sd1Id,
      planId,
      nr: '1',
      pijler: 'Onderwijs & Kwaliteit',
      dienst: 'Pedagogische dienst',
      rubriek: 'Leerresultaten',
      probleem: 'Het slagingspercentage in taalcursussen ligt onder het gewenste niveau.',
      doel: 'Het slagingspercentage in taalcursussen met 10% verhogen tegen einde schooljaar.',
      meting: 'Slagingspercentage per cursus meten via rapport juni 2026.',
      typeGoal: 'SD',
      verantwoordelijken: ['Jan Peeters'],
      uitvoerders: ['Jan Peeters', 'Marie Claes'],
      startDate: '2025-09-01',
      endDate: '2026-06-30',
      adjustedEndDate: '',
      status: 'in_uitvoering',
      notes: '',
      createdAt: now,
      updatedAt: now,
      createdBy: SYSTEM,
      updatedBy: '',
    },
    {
      id: sd2Id,
      planId,
      nr: '2',
      pijler: 'Organisatie & Personeel',
      dienst: 'HR',
      rubriek: 'Professionele ontwikkeling',
      probleem: 'Nascholing wordt onvoldoende systematisch bijgehouden.',
      doel: 'Een systematisch nascholingsbeleid uitwerken voor alle personeelsleden.',
      meting: 'Jaarlijks nascholingsplan aanwezig + 90% deelname.',
      typeGoal: 'SD',
      verantwoordelijken: ['Sofie Vermeersch'],
      uitvoerders: ['Sofie Vermeersch', 'Directie'],
      startDate: '2025-09-01',
      endDate: '2026-06-30',
      adjustedEndDate: '',
      status: 'niet_gestart',
      notes: '',
      createdAt: now,
      updatedAt: now,
      createdBy: SYSTEM,
      updatedBy: '',
    },
  ]

  const ods: OperationalObjective[] = [
    {
      id: od1Id,
      planId,
      sdId: sd1Id,
      nr: '1.1',
      probleem: 'Lesmateriaal sluit onvoldoende aan bij de leefwereld van cursisten.',
      doel: 'Vernieuwd en aantrekkelijk lesmateriaal ontwikkelen voor NT2-cursussen.',
      meting: 'Nieuw materiaal beschikbaar voor sept 2025, tevredenheidsscore > 7/10.',
      typeGoal: 'OD',
      verantwoordelijken: ['Marie Claes'],
      uitvoerders: ['Marie Claes', 'Peter Janssen'],
      startDate: '2025-09-01',
      endDate: '2026-01-31',
      adjustedEndDate: '',
      status: 'in_uitvoering',
      notes: '',
      createdAt: now,
      updatedAt: now,
      createdBy: SYSTEM,
      updatedBy: '',
    },
    {
      id: od2Id,
      planId,
      sdId: sd1Id,
      nr: '1.2',
      probleem: 'Differentiatie binnen cursusgroepen is moeilijk.',
      doel: 'Differentiatiestrategie implementeren in alle taalcursussen.',
      meting: 'Alle lesgevers volgen bijscholing differentiatie voor feb 2026.',
      typeGoal: 'OD',
      verantwoordelijken: ['Jan Peeters'],
      uitvoerders: ['Jan Peeters'],
      startDate: '2026-01-01',
      endDate: '2026-06-30',
      adjustedEndDate: '',
      status: 'niet_gestart',
      notes: '',
      createdAt: now,
      updatedAt: now,
      createdBy: SYSTEM,
      updatedBy: '',
    },
    {
      id: od3Id,
      planId,
      sdId: sd2Id,
      nr: '2.1',
      probleem: 'Nascholingsbehoeften worden niet structureel bevraagd.',
      doel: 'Jaarlijkse bevraging nascholingsbehoeften organiseren.',
      meting: 'Bevraging afgenomen voor okt 2025, rapport klaar nov 2025.',
      typeGoal: 'OD',
      verantwoordelijken: ['Sofie Vermeersch'],
      uitvoerders: ['Sofie Vermeersch'],
      startDate: '2025-09-01',
      endDate: '2025-11-30',
      adjustedEndDate: '',
      status: 'niet_gestart',
      notes: '',
      createdAt: now,
      updatedAt: now,
      createdBy: SYSTEM,
      updatedBy: '',
    },
    {
      id: od4Id,
      planId,
      sdId: sd2Id,
      nr: '2.2',
      probleem: 'Er is geen overzicht van gevolgde nascholingen.',
      doel: 'Centraal register nascholingen opzetten en bijhouden.',
      meting: 'Register operationeel voor jan 2026, maandelijks bijgewerkt.',
      typeGoal: 'OD',
      verantwoordelijken: ['Sofie Vermeersch'],
      uitvoerders: ['Sofie Vermeersch', 'Secretariaat'],
      startDate: '2025-11-01',
      endDate: '2026-06-30',
      adjustedEndDate: '',
      status: 'niet_gestart',
      notes: '',
      createdAt: now,
      updatedAt: now,
      createdBy: SYSTEM,
      updatedBy: '',
    },
  ]

  const actions: Action[] = [
    {
      id: uuid(),
      planId,
      odId: od1Id,
      title: 'Inventariseren huidig lesmateriaal',
      verantwoordelijke: 'Marie Claes',
      uitvoerders: ['Marie Claes'],
      startDate: '2025-09-01',
      endDate: '2025-10-01',
      adjustedEndDate: '',
      status: 'afgerond',
      opmerkingen: 'Inventaris afgewerkt op 28 sept.',
      createdAt: now,
      updatedAt: now,
      createdBy: SYSTEM,
      updatedBy: '',
    },
    {
      id: uuid(),
      planId,
      odId: od1Id,
      title: 'Nieuw materiaal ontwerpen (NT2 module 1-3)',
      verantwoordelijke: 'Marie Claes',
      uitvoerders: ['Marie Claes', 'Peter Janssen'],
      startDate: '2025-10-01',
      endDate: '2025-12-15',
      adjustedEndDate: '',
      status: 'in_uitvoering',
      opmerkingen: '',
      createdAt: now,
      updatedAt: now,
      createdBy: SYSTEM,
      updatedBy: '',
    },
    {
      id: uuid(),
      planId,
      odId: od1Id,
      title: 'Piloottest nieuw materiaal',
      verantwoordelijke: 'Marie Claes',
      uitvoerders: ['Marie Claes', 'Peter Janssen'],
      startDate: '2026-01-05',
      endDate: '2026-01-31',
      adjustedEndDate: '',
      status: 'niet_gestart',
      opmerkingen: '',
      createdAt: now,
      updatedAt: now,
      createdBy: SYSTEM,
      updatedBy: '',
    },
    {
      id: uuid(),
      planId,
      odId: od2Id,
      title: 'Bijscholing differentiatie organiseren',
      verantwoordelijke: 'Jan Peeters',
      uitvoerders: ['Jan Peeters'],
      startDate: '2026-01-15',
      endDate: '2026-02-28',
      adjustedEndDate: '',
      status: 'niet_gestart',
      opmerkingen: '',
      createdAt: now,
      updatedAt: now,
      createdBy: SYSTEM,
      updatedBy: '',
    },
    {
      id: uuid(),
      planId,
      odId: od3Id,
      title: 'Vragenlijst nascholingsbehoeften opstellen',
      verantwoordelijke: 'Sofie Vermeersch',
      uitvoerders: ['Sofie Vermeersch'],
      startDate: '2025-09-01',
      endDate: '2025-09-30',
      adjustedEndDate: '',
      status: 'niet_gestart',
      opmerkingen: '',
      createdAt: now,
      updatedAt: now,
      createdBy: SYSTEM,
      updatedBy: '',
    },
    {
      id: uuid(),
      planId,
      odId: od4Id,
      title: 'Softwaretool selecteren voor register',
      verantwoordelijke: 'Sofie Vermeersch',
      uitvoerders: ['Sofie Vermeersch'],
      startDate: '2025-11-01',
      endDate: '2025-11-30',
      adjustedEndDate: '2025-12-15',
      status: 'uitgesteld',
      opmerkingen: 'Vertraging door leveranciersprobleem.',
      createdAt: now,
      updatedAt: now,
      createdBy: SYSTEM,
      updatedBy: '',
    },
  ]

  const users: User[] = [
    {
      id: 'admin-user',
      name: 'Admin Gebruiker',
      email: 'admin@cvo.be',
      role: 'admin',
      scopes: [],
      isActive: true,
    },
    {
      id: 'jan-peeters',
      name: 'Jan Peeters',
      email: 'jan.peeters@cvo.be',
      role: 'verantwoordelijke',
      scopes: [planId],
      isActive: true,
    },
    {
      id: 'marie-claes',
      name: 'Marie Claes',
      email: 'marie.claes@cvo.be',
      role: 'editor',
      scopes: [planId],
      isActive: true,
    },
    {
      id: 'sofie-vermeersch',
      name: 'Sofie Vermeersch',
      email: 'sofie.vermeersch@cvo.be',
      role: 'verantwoordelijke',
      scopes: [planId],
      isActive: true,
    },
  ]

  await db.transaction('rw', [db.plans, db.strategicObjectives, db.operationalObjectives, db.actions, db.users], async () => {
    await db.plans.add(plan)
    await db.strategicObjectives.bulkAdd(sds)
    await db.operationalObjectives.bulkAdd(ods)
    await db.actions.bulkAdd(actions)
    await db.users.bulkAdd(users)
  })
}
